--- 
default: 
  adapter: sqlite3
  encoding: unicode
  pool: 5
  timeout: 5000
development: 
  adapter: sqlite3
  database: blog_development
  encoding: unicode
  pool: 5
  timeout: 5000
production: 
  adapter: postgresql
  database: blog
  encoding: unicode
  password: "<%= ENV['BLOG_DATABASE_PASSWORD'] %>"
  pool: 5
  timeout: 5000
  url: "<%= ENV['DATABASE_URL'] %>"
  username: "<%= ENV['BLOG_DATABASE_USERNAME'] %>"
test: 
  adapter: sqlite3
  database: blog_test
  encoding: unicode
  pool: 5
  timeout: 5000
